name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Generate 0 or 1
        id: generate_number
        run:  echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
        
      - name: Pass or fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then echo 1; else echo 0; fi

      - name: files
        id: filess
        run: |
          cat >> difference.sh <<END
            #!/bin/bash
            
            frontend=0
            backend=0
            export BACKEND=$backend
            export FRONTEND=$frontend
          END
          chmod +x difference.sh
          source ./difference.sh
          echo "backend=$BACKEND" >> $GITHUB_OUTPUT
          echo "frontend=$FRONTEND" >> $GITHUB_OUTPUT
          
      - name: print
        if: ${{ steps.filess.outputs.backend == 1 }}
        run: echo "HELLO"
