name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Generate 0 or 1
        id: generate_number
        run:  echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
        
      - name: Pass or fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then echo 1; else echo 0; fi

      - name: files
        id: filess
        run: |
          cat >> difference.sh <<END
            frontend=0
            backend=0
            git diff --name-only HEAD^ HEAD >> diff.txt
            if grep -q "frontend" diff.txt; then
              echo "changes present in frontend"
              frontend=1
            fi
            if grep -q "backend" diff.txt; then
              echo "Changes present in backend"
              backend=1
            fi
            echo "BACKEND=$backend" >> $GITHUB_OUTPUT
            echo "FRONTEND=$frontend" >> $GITHUB_OUTPUT
          END
          
      - name: print
        run: echo ${{ steps.filess.outputs.BACKEND }}
